= Equipment and Facilities Relevant to the FNNDSC

== Overview

This repository provides a central location for grant-ready supporting documents useful for inserting into _Facilities and Resources_ and _Equipment_ documents. Typically these are required by NIH applications, and in this repository are various source documents for the Fetal Neonatal Neuroimaging Development Science Center (https://fnndsc.org[FNNDSC]) at Boston Children's Hospital (https://www.childrenshospital.org/research/centers/fetal-neonatal-neuroimaging-and-developmental-science-center-research[BCH]).

== Organization

The source of truth, or reference documentation, is in the `adoc` directory. This contains several files, some with the prefix _equipment_ (for NIH "Equipment" documentation) and others with the prefix _facilities_ (for NIH "Facilities and Resources" documentation). The contents of these documents are intended to be mix-and-match for a specific application and context and should be rather self-evident.

Please note that these are written in AsciiDoc format (see https://en.wikipedia.org/wiki/AsciiDoc[here]) and despite the `doc` in the suffix have _nothing_ to do with Microsoft Word.

== Wait? What is AsciiDoc? That's not Word?

Yes. Astute observation. The core files here are not `docx` but plain old universally readable and friendly and slightly marked-up text. For example _this_ document itself was written in AsciiDoc format -- note how `github` nicely formats and displays it. Being text based, it's a more easily accessible, editable, and sharable format. Perfect for capturing information.

You might wonder, "What's markup?". Well, you can think of it like `html` or any format that embeds formatting instructions into a text document. For instance, in AsciiDoc to make a word **bold** we simply pre-and post-fix it with two asterisks:

[literal]
----
To make the FNNDSC bold, we just do **FNNDSC**!
----

"To make the FNNDSC bold, we just do **FNNDSC**!"

AsciiDoc markup doesn't really interfere with reading the text document to a human, and being text can be easily converted to many other formats. Microsoft Word, despite being widely used by many researchers to create documentation, is not an ideal format for storing information. Firstly, it is a _terminal_ format, meaning it is quite difficult to convert easily into other format (such as LaTeX or html, or even pdf). Secondly, being a proprietary, binary format it requires complex tools to simply read and edit. You often have to actually download a Word file to just simply view it.

Text, on the other hand, is a universal format. Thus, the decision was made to use a text-based format to capture information and then _convert_ this text into output formats as needed. Hence, AsciiDoc was selected due to its simple text-based light markdown, ease of editing, simplicity in copying into other documents, and also ability to be processed by other toolchains into many formats.

== Just where are the Word doc files?

You might be wondering, "Ok. Fine. I get it. Text is good. Word is... less good?" Still you might quite legitimately feel, "Please can I just have Word files anyway?" I don't want to copy marked up text into my Word doc and then go and format it manually.

No worries.  We got you. Just look in the `docx` directory for Word files. Please note that these were _automatically_ generated from the `adoc` sources, so changing/updating the Word files for this repo is not recommended. Rather, we prefer/ask you update the text `adoc` files and we can then create new `docx` derivatives.

Currently, this repository contains `pdf`, `html` and `docx` conversions of the core AsciiDoc text files.

== What are the other directories?

You'll notice there are several other directories. The `html` and `pdf` directories should be pretty obvious and contain `html` and `pdf` derivatives of the original `adoc` files.

The `tex` and `tex-pdf` might seem a bit unfamiliar. First off, the `tex` directory contains LaTeX formatted files (LaTeX is another text file type used very much in physical sciences, engineering, and mathematics). The `tex-pdf` is simply the output `tex` files that have been converted to `pdf` by the `xelatex` program, available for easy install on most Linux distros and on macOS with `homebrew`). These pdf outputs look a bit different than the ones in the `pdf` directory, and are included just for completeness sake -- showing how the `tex` files might be converted using a LaTeX engine.

== How to use?

=== The easy way

Depending on what you want, you can just click on the files in the `adoc` directory in your web browser and just straight up copy/paste text into your grant document. Or, you can download the `docx` derivatives by clicking on them in your browser, and then choosing the "Download" icon on the top left. Once copied to your computer, you can then copy/paste/use as you see fit.

=== The more advanced way

If you know `github` and are on Linux (or possibly macOS) you can just clone this repo

[source,console]
cd ~/somedir
git clone https://github.com/FNNDSC/facilities_resources

to pull the repo. If you want to make changes to the `adoc` and then automatically generate updated `docx` derivatives:

[source,console]
----
#
# to build the derivatives you need
# 'make', 'asciidoctor', 'asciidoctor-pdf', 'pandoc', 'asciidoctor-latex'
# (some packages might need `gem` to be installed, i.e.
#   gem install asciidoctor-latex --pre
#)
#
# on `arch` linux you might do
# yay -S texlive-extra texlive-science texlive-mhchem-bundle
cd facilities_resources
make

# if you want to clean things up, do
make clean

# if you just want say the docs outputs, do
make clean
make docx
----

== Contributions welcome!

If you have updates/suggestions etc, please let us know and we can all help to keep these documents up to date.

_-30-_