= Facilities and Other Resources

== Boston Children's Hospital (BCH)

Boston Children’s Hospital (BCH) is home to the world’s largest research enterprise at a pediatric center, and operates at the forefront of pediatric clinical care in translating new research discoveries into clinical practice. Since 1869, the focus at BCH has been on giving every child the best chance at a healthy life. BCH combines the power of compassionate care and pioneering research (home to two Nobel Prize winners and dozens of members of the National Academies) to better understand disease and to transform that knowledge into innovative treatments, preventive measures, and even cures. BCH is the home to many firsts — from the first surgery to repair a heart defect in a child, to culturing the first polio virus, to the development of chemotherapy to treat acute lymphocytic leukemia in children. With more than 40 clinical departments and 258 specialized clinical programs, BCH is one of the largest pediatric medical centers in the United States. The BCH science environment houses a high concentration of world class researchers, where basic studies are extensively informed by close contacts with the clinical programs within the hospital. The research enterprise at BCH, comprising more than 3,000 researchers, is the world’s largest at a pediatric center. Geographically, BCH is located at the heart of the world-renowned Longwood Medical Area (LMA) and is within easy walking distance to five other major research institutions: Harvard Medical School, Dana-Farber Cancer Institute, Brigham and Women’s Hospital, Joslin Diabetes Center, and Beth Israel Deaconess Medical Center. The abundance of scientific talent in such close quarters allows for an extremely collaborative environment both within and outside the walls of BCH. The close proximity of the researchers in this area creates a tremendous advantage, as scientists can be easily connected to other acclaimed experts in most fields of medical research to jumpstart novel ideas. The highly collaborative community, in addition to the strong emphasis that BCH places in trainee professional and scientific development, contributes to the likelihood of success for all research endeavors.

=== Clinical

==== Department of Radiology

BCH Department of Radiology is the nation’s oldest and largest pediatric imaging group and home to the largest pediatric neuroradiology subspecialty group. Currently, there are over 200,000 imaging studies that are performed each year. In addition to pediatric radiologists, pediatric neuro-radiologists and interventional radiologists, all of whom have received additional training in childhood anatomy and diseases, there are nuclear medicine physicians, nurse practitioners, technologists, nurses and child life specialists, all experienced in helping and caring for children. It is recognized for excellence in clinical care and has as its goal, the development of cutting edge pediatric imaging. In addition to CT, Ultrasound and PET facilities, the Radiology Department manages seven state-of-the-art 3T MRIs and two 1.5T MRIs, one of which is located in the intraoperative suite. All the 3T systems are equipped with 32- and 64- channel commercial head coils, 60- channel body array coils for fast, high-resolution imaging. The 3T MRI systems let clinicians achieve faster scans and higher image resolution than the more commonly used 1.5T machines. Additionally, BCH houses MRI coils designed to fit nearly every body size and anatomic location. Motion-correction software customized for patients by specialized physicists and physicians compensates for pediatric patients who may have difficulty lying still. Active research funding has also developed motion mitigated protocols for neuroimaging, fast three-dimensional spectroscopic imaging, and time-efficient, highly accelerated structural diffusion and functional imaging.

==== Maternal Fetal Care Center

The Maternal Fetal Care Center (MFCC) of BCH was founded in 2000 to treat the fetus with life-threatening congenital anomalies. Since its inception, thousands of pregnant women have been referred to the MFCC for diagnostic studies, counseling, treatment and care when a fetal anomaly is suspected or diagnosed. Few centers offer the depth and breadth of expertise found at BCH. The MFCC is one of just a handful of comprehensive fetal care centers in the United States and the only one to offer fetal surgical interventions in the Northeast. The MFCC currently sees over 2500 patients a year with numbers rising as we are introducing more fetal interventions with the arrival of two fetal surgeons. In particular, the MFCC is a referral site for monochorionic diamniotic twins to screen for twin-to-twin transfusion syndrome and when appropriate, to treat with fetoscopic laser surgery. About 30 - 50 of these laser surgeries are anticipated per year. Through groundbreaking procedures and a commitment to the best in pediatric care, the center is rewriting what is possible in fetal medicine and surgery with their staff of specialists, representing more than 20 specialty areas.

=== Laboratory

==== Department of Radiology

The Department of Radiology is one of the largest and well-known pediatric radiology programs in the USA. MRI: The main MRI facility in Boston is located on the second floor of the main hospital, near the hospital’s entrance. Additional MRI space on the main campus can be found in the Mandell Building, which is a 116,000-square-foot, ten-story, state-of-the-art clinical building that opened in 2013. This building houses a much needed expansion space for Radiology, Surgery, Neurology, and Pharmacy services. Additional MRI space on the main campus can now also be found in the recently completed Hale Family Building, an eleven-story state-of-the-art clinical building that opened in 2023. This building houses the much needed expansion space for Radiology, Surgery, Newborn Medicine, the Heart Center, as well additional single inpatient rooms and collaboration spaces. In the main MRI facility, there are five inpatient 3T systems (two Siemens Skyra, two Siemens Vida and one Siemens Prisma) and one 1.5T system (Siemens Avanto). One dedicated research scanner, a 3T Siemens Prisma is located about one mile from the main hospital, at 2 Brookline Place Facility. One 3T system (Siemens Tim Trio) is located at the BCH’s branch in Waltham, MA, and one 3T system (Siemens Verio) resides in Peabody, MA. All of these MRI scanners are available for both clinical and research studies. In addition, there is a recently constructed research MR facility at 2 Brookline space, a mile from the main campus that has a dedicated research MRI. More details about these scanners are given in the “Equipment” section of this grant. Throughout each facility, there are imaginative décor and dedicated staff to help make the patient’s experience as enjoyable as possible. Age-appropriate distraction techniques, including video goggles, music and lighting, are used to help ease anxiety and avoid sedation whenever possible.
